config/routes.rb
Rails.application.routes.draw do
  resources :charts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "charts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
    @keep = Chart.group(:distance).count
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chart_params
      params.require(:chart).permit(:planet, :distance, :temperature)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_with(model: chart, local: true) do |form| %>
  <% if chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
        <% chart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :planet %>
    <%= form.text_field :planet %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance %>
  </div>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.text_field :temperature %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Charts</h1>
<div style="width: 1000px">
  <%= line_chart(@keep) %>
</div>


<table>
  <thead>
    <tr>
      <th>Planets</th>
      <th>Distance</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= chart.planet %></td>
        <td><%= chart.distance %></td>
        <td><%= chart.temperature %></td>
        <td><%= link_to 'Show', chart %></td>
        <td><%= link_to 'Edit', edit_chart_path(chart) %></td>
        <td><%= link_to 'Destroy', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chart', new_chart_path %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Planet:</strong>
  <%= @chart.planet %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @chart.distance %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @chart.temperature %>
</p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>